# https://docs.travis-ci.com/user/reference/bionic
# https://docs.travis-ci.com/user/installing-dependencies
language: c++
jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

before_install:
  - ./install_deps.sh
  - ./install_opencv.sh

script:
  - ./install_openrealm_lib.sh
