# https://docs.travis-ci.com/user/reference/bionic
# https://docs.travis-ci.com/user/installing-dependencies
language: c++
jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: focal
services:
  - docker

before_install:
  - docker pull khedar/openrealm-base:latest
  - docker run -it -d --name build khedar/openrealm-base:latest bash
  - wget https://raw.githubusercontent.com/laxnpander/OpenREALM/dev/tools/install_deps.sh

script:
  - docker exec build bash /install_openrealm_lib.sh
