# https://docs.travis-ci.com/user/reference/bionic
# https://docs.travis-ci.com/user/installing-dependencies
language: c++
jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: focal
services:
  - docker

before_install:
  - docker pull laxnpander/openrealm-base:latest
  - docker run -it -d --name build laxnpander/openrealm-base:latest bash
  - wget https://raw.githubusercontent.com/laxnpander/OpenREALM/dev/tools/install_deps.sh
  - wget https://raw.githubusercontent.com/laxnpander/OpenREALM/dev/tools/install_openrealm_lib.sh

script:
  - docker exec -i build bash < install_deps.sh
  - docker exec -i build bash < install_openrealm_lib.sh
