# https://docs.travis-ci.com/user/reference/bionic
# https://docs.travis-ci.com/user/installing-dependencies
language: c++
jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
services:
  - docker

before_install:
  - docker pull khedar/openrealm-base:latest
  - docker run -it -d --name build khedar/openrealm-base:latest bash

script:
  - docker exec build bash ./tools/install_openrealm_lib.sh